# Site settings
title: Koyomiya Docs
description: > # this means to ignore newlines until "baseurl:"
  Koyomiya
twitter_username: koyomiyahouya
github_username:  koyomiyahouya

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]
